<?xml version="1.0" encoding="utf-8" standalone="yes"?>

  <!DOCTYPE translator [<!-- Document -->
   <!ELEMENT translator (family)>
   <!-- Top level elements -->
   <!ELEMENT family (description,members)>
   <!ATTLIST family name CDATA #REQUIRED>
   <!ELEMENT description (brief,full,features)>
   <!ELEMENT members (name,description)>
   <!ELEMENT member (description,replacements)>
   <!ATTLIST member name CDATA #REQUIRED>
   <!-- Description elements -->
   <!ELEMENT brief (#PCDATA)>
   <!ELEMENT full (#PCDATA)>
   <!ELEMENT features (feature)>
   <!-- Feature elements -->
   <!ELEMENT feature (#PCDATA)>
   <!-- Replacements -->
   <!ELEMENT replacements (replacement)>
   <!ELEMENT replacement (#PCDATA)>
   <!ATTLIST replacement elemtag CDATA #REQUIRED>
   <!ATTLIST replacement toggle (on|off) "on">
   <!ATTLIST replacement member CDATA #IMPLIED> 
   <!-- The five standard entities -->
   <!ENTITY lt "&#38;#60;">
   <!ENTITY gt "&#62;">
   <!ENTITY amp "&#38;#38;">
   <!ENTITY apos "&#39;">
   <!ENTITY quot "&#34;">
   <!-- prTemplate basic entities -->
   <!ENTITY tmplBasename "tmplBasename">
   <!ENTITY tmplCreationDate "tmplCreationDate">
   <!ENTITY tmplAuthor "tmplAuthor">
  ]>

  <translator>
    <family name="kert">
      <description>
        <short>
          Basic documents for the kert suite
        </short>
        <features>
          <feature>Title page</feature>
          <feature>latexmk</feature>
        </features>
      </description>
      <members>
        <!-- ALL =================================== -->
        <member name="ALL">
          <description>
            <short>
              Common features: title page, technical packages, latexmk (Linux)
            </short>
          </description>
          <replacements>
            <replacement elemtag="tmplPackagesProvidesPackage">
              \ProvidesPackage{&tmplBasename;-packages}[&tmplCreationDate; v1.0 (&tmplAuthor;)]
            </replacement>
            <replacement elemtag="tmplMacrosProvidesPackage">
              \ProvidesPackage{&tmplBasename;-macros}[&tmplCreationDate; v1.0 (&tmplAuthor;)]
            </replacement>
            <replacement elemtag="tmplPagesProvidesPackage">
              \ProvidesPackage{&tmplBasename;-pages}[&tmplCreationDate; v1.0 (&tmplAuthor;)]
            </replacement>
            <replacement elemtag="tmplCfgProvidesPackage">
              \ProvidesPackage{&tmplBasename;-cfg}[&tmplCreationDate; v1.0 (&tmplAuthor;)]
            </replacement>
            <replacement elemtag="tmplCfgPrLogo">
              \newcommand*{\prLogo}{Glass-Sun-Moon-soft}
            </replacement>
            <replacement elemtag="tmplMainProjectPreamble">
              \usepackage{&tmplBasename;-packages}
              \usepackage{&tmplBasename;-cfg}
              \usepackage[prdraft]{&tmplBasename;-pages}
              \usepackage{&tmplBasename;-macros}
            </replacement>
            <replacement elemtag="tmplMainLoadAcronyms">
              \loadglsentries{&tmplBasename;-Acronyms}
            </replacement>
            <replacement elemtag="tmplMainBoilerplate">
              \input{&tmplBasename;_unit_Report}
            </replacement>
            <replacement elemtag="tmplMainLoadBibliography">
              \bibliography{&tmplBasename;}
            </replacement>
          </replacements>
        </member>
        <!-- Technical Note =================================== -->
        <member name="Technical Note">
          <description>
            <short>
              Document technical ideas, techniques, methods, insights, etc. 
            </short>
          </description>
          <replacements>
            <replacement elemtag="tmplCfgPrReportType">
              \newcommand*{\prReportType}{Technical Note}
            </replacement>
            <replacement elemtag="tmplCfgPrID">
              \newcommand*{\prID}{TN-YYYY-uid}
            </replacement>
            <replacement elemtag="tmplMainBoilerplate">
              \input{&tmplBasename;_unit_Technical-Note}
            </replacement>
            <replacement elemtag="tmplMainCoverPage">
              %\prCoverPage[noblankpage]
              %\prCoverPage              
            </replacement>
          </replacements>
        </member>
        <!-- Concept Calculation =================================== -->
        <member name="Concept Calculation">
          <description>
            <short>
              Description and verification of calculation from input to output.
            </short>
          </description>
          <replacements>
            <replacement elemtag="tmplCfgPrReportType">
              \newcommand*{\prReportType}{Concept Calculation}
            </replacement>
            <replacement elemtag="tmplCfgPrID">
              \newcommand*{\prID}{CC-YYYY-uid}
            </replacement>
            <replacement elemtag="tmplMainBoilerplate">
              \input{&tmplBasename;_unit_Concept-Calculation}
            </replacement>
          </replacements>
        </member>
        <!-- Technical Report =================================== -->
        <member name="Technical Report">
          <description>
            <short>
              Report the results of a project.
            </short>
          </description>
          <replacements>
            <replacement elemtag="tmplCfgPrReportType">
              \newcommand*{\prReportType}{Technical Report}
            </replacement>
            <replacement elemtag="tmplCfgPrID">
              \newcommand*{\prID}{TR-YYYY-uid}
            </replacement>
            <replacement elemtag="tmplMainBoilerplate">
              \input{&tmplBasename;_unit_Technical-Report}
            </replacement>
          </replacements>
        </member>
      </members>
    </family>
  </translator>
